### ISSUE TITLE
datasetのファイルパス

### ISSUE THREAD

**Issue by KanHatakeyama** [ce-lery/japanese-mistral-300m-recipe#3]
repo作成ありがとうございます｡記事を拝見しながら､動かし中です｡

pretrainでエラーが出ました｡

恐らく､
https://github.com/ce-lery/japanese-mistral-300m-recipe/blob/v0.1.0/pretrain/train/hf_config.json
の
    "train_file":"../dataset/archive/train.txt",
    "validation_file":"../dataset/archive/test.txt",
は
    "train_file":"../dataset/train.txt",
    "validation_file":"../dataset/test.txt",
な気がしました｡pathを変えたら動きました｡

**Comment by ce-lery** [comment]
ご使用いただきありがとうございます。
ご指摘のとおりです、申し訳ありません。修正内容を反映し、v.0.1.1をリリースいたしました。
https://github.com/ce-lery/japanese-mistral-300m-recipe/commit/ce1b56d400a40bb42dc717ddac0d1158c7f3e117

ご指摘いただいたtrain_file、validation_fileのパスを修正いただければ、その他はそのままv0.1.0の内容で動作するかと思います。
また何かありましたらご指摘いただけますと幸いです。よろしくお願いいたします。

P.S. 先生のDiscordチャンネル、いつも楽しく拝見させて頂いております。

**Comment by KanHatakeyama** [comment]
ありがとうございます!
現在計算中ですので､また何かあれば報告します｡
引き続きよろしくお願いします｡

**Comment by ce-lery** [comment]
この問題は解決したのでcloseします。
